export class ModRecommendationService {
  constructor(modRecRepo) { this.repo = modRecRepo; }
  async submitRecommendation(payload) { try { if (!payload.submitter_name?.trim()) return { success: false, error: 'Submitter name is required.' }; if (!payload.submitter_discord?.trim()) return { success: false, error: 'Discord tag is required.' }; if (!payload.mod_name?.trim()) return { success: false, error: 'Mod name is required.' }; if (!payload.mod_link?.trim()) return { success: false, error: 'Mod link/URL is required.' }; if (!this._isValidUrl(payload.mod_link)) return { success: false, error: 'Please provide a valid URL.' }; if (payload.submitter_name.length > 255) return { success: false, error: 'Submitter name is too long (max 255 characters).' }; if (payload.mod_name.length > 255) return { success: false, error: 'Mod name is too long (max 255 characters).' }; const normalizedPayload = { submitter_name: payload.submitter_name.trim(), submitter_discord: payload.submitter_discord.trim(), mod_name: payload.mod_name.trim(), mod_link: payload.mod_link.trim(), mod_category: payload.mod_category?.trim() || null, reason: payload.reason?.trim() || null }; const { data, error } = await this.repo.insert(normalizedPayload); if (error) { console.error('Insert error:', error); return { success: false, error: 'Failed to submit recommendation. Please try again.' }; } return { success: true, data: { id: data.id, status: 'pending' } }; } catch (err) { console.error('submitRecommendation error:', err); return { success: false, error: err.message || 'An error occurred.' }; } }
  async getRecommendations(status = null) { try { if (status && !['pending','approved','denied'].includes(status)) return { success: false, error: 'Invalid status filter.' }; const { data, error } = await this.repo.getAll(status); if (error) { console.error('ModRecommendationService.getRecommendations error:', { status, error: error.message || error, code: error.code, details: error.details }); return { success: false, error: `Failed to fetch recommendations: ${error.message || JSON.stringify(error)}` }; } return { success: true, data }; } catch (err) { console.error('ModRecommendationService.getRecommendations exception:', err); return { success: false, error: err.message }; } }
  async getRecommendation(id) { try { const { data, error } = await this.repo.getById(id); if (error || !data) return { success: false, error: 'Recommendation not found.' }; return { success: true, data }; } catch (err) { return { success: false, error: err.message }; } }
  async updateRecommendationStatus(id, status, admin_comment = null) { try { if (!['pending','approved','denied'].includes(status)) return { success: false, error: 'Invalid status value.' }; if (admin_comment && admin_comment.length > 1000) return { success: false, error: 'Comment is too long (max 1000 characters).' }; const { data, error } = await this.repo.updateStatus(id, status, admin_comment); if (error || !data) return { success: false, error: 'Failed to update recommendation.' }; return { success: true, data }; } catch (err) { return { success: false, error: err.message }; } }
  async deleteRecommendation(id) { try { const { error } = await this.repo.delete(id); if (error) return { success: false, error: 'Failed to delete recommendation.' }; return { success: true }; } catch (err) { return { success: false, error: err.message }; } }
  async getStats() { try { const [pending, approved, denied] = await Promise.all([ this.repo.count('pending'), this.repo.count('approved'), this.repo.count('denied') ]); return { success: true, data: { pending: pending.data || 0, approved: approved.data || 0, denied: denied.data || 0, total: (pending.data || 0) + (approved.data || 0) + (denied.data || 0) } }; } catch (err) { return { success: false, error: err.message }; } }
  _isValidUrl(url) { try { new URL(url); return true; } catch { return false; } }
}
